_wandb:
    value:
        cli_version: 0.23.0
        e:
            jj4g2tzkp6yupr5xun0cjvdzp5w1sp8u:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "4294967296"
                codePath: tools/upload_wandb.py
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "319975084032"
                email: gabrielorlow@discente.ufg.br
                executable: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
                git:
                    commit: 268f805b644d504b1298ea96418866dff22f8183
                    remote: git@github.com:orlow04/football.git
                host: macbook-pro-orlow.local
                memory:
                    total: "19327352832"
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/orlow/dev/rl/final/getafe-ball/tools/upload_wandb.py
                python: CPython 3.12.5
                root: /Users/orlow/dev/rl/final/getafe-ball/football/gfootball/examples
                startedAt: "2025-11-26T22:04:16.347125Z"
                writerId: jj4g2tzkp6yupr5xun0cjvdzp5w1sp8u
        m: []
        python_version: 3.12.5
        t:
            "3":
                - 2
                - 16
            "4": 3.12.5
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
trial_dir:
    value: /Users/orlow/dev/rl/final/getafe-ball/ray_results/PPO_gfootball_defensive_a8710_00000_0_2025-11-26_19-46-53
